var Level3 = {
  id: 3,
  nombre: 'Palabras',
  ejercicios: [
    { id: 'w1', objetivo: 'animales', texto: 'elefante', imagen: '🐘', pista: 'E-LE-FAN-TE' },
    { id: 'w2', objetivo: 'animales', texto: 'mariposa', imagen: '🦋', pista: 'MA-RI-PO-SA' },
    { id: 'w3', objetivo: 'animales', texto: 'tortuga', imagen: '🐢', pista: 'TOR-TU-GA' },
    { id: 'w4', objetivo: 'animales', texto: 'conejo', imagen: '🐰', pista: 'CO-NE-JO' },
    { id: 'w5', objetivo: 'animales', texto: 'jirafa', imagen: '🦒', pista: 'JI-RA-FA' },
    { id: 'w6', objetivo: 'animales', texto: 'delfín', imagen: '🐬', pista: 'DEL-FÍN' },
    { id: 'w7', objetivo: 'comida', texto: 'manzana', imagen: '🍎', pista: 'MAN-ZA-NA' },
    { id: 'w8', objetivo: 'comida', texto: 'chocolate', imagen: '🍫', pista: 'CHO-CO-LA-TE' },
    { id: 'w9', objetivo: 'comida', texto: 'helado', imagen: '🍦', pista: 'HE-LA-DO' },
    { id: 'w10', objetivo: 'comida', texto: 'sandía', imagen: '🍉', pista: 'SAN-DÍ-A' },
    { id: 'w11', objetivo: 'casa', texto: 'ventana', imagen: '🪟', pista: 'VEN-TA-NA' },
    { id: 'w12', objetivo: 'casa', texto: 'cocina', imagen: '🍳', pista: 'CO-CI-NA' },
    { id: 'w13', objetivo: 'casa', texto: 'baño', imagen: '🛁', pista: 'BA-ÑO' },
    { id: 'w14', objetivo: 'casa', texto: 'jardín', imagen: '🌺', pista: 'jar-DÍN' },
    { id: 'w15', objetivo: 'cuerpo', texto: 'cabeza', imagen: '🗣️', pista: 'CA-BE-ZA' },
    { id: 'w16', objetivo: 'cuerpo', texto: 'brazo', imagen: '💪', pista: 'BRA-ZO' },
    { id: 'w17', objetivo: 'cuerpo', texto: 'pierna', imagen: '🦵', pista: 'PIER-NA' },
    { id: 'w18', objetivo: 'cuerpo', texto: 'mano', imagen: '✋', pista: 'MA-NO' },
    { id: 'w19', objetivo: 'colores', texto: 'morado', imagen: '🟣', pista: 'MO-RA-DO' },
    { id: 'w20', objetivo: 'colores', texto: 'rosa', imagen: '🩷', pista: 'RO-SA' },
    { id: 'w21', objetivo: 'colores', texto: 'naranja', imagen: '🟠', pista: 'NA-RAN-JA' },
    { id: 'w22', objetivo: 'ropa', texto: 'zapato', imagen: '👟', pista: 'ZA-PA-TO' },
    { id: 'w23', objetivo: 'ropa', texto: 'sombrero', imagen: '👒', pista: 'SOM-BRE-RO' },
    { id: 'w24', objetivo: 'ropa', texto: 'vestido', imagen: '👗', pista: 'VES-TI-DO' },
    { id: 'w25', objetivo: 'naturaleza', texto: 'montaña', imagen: '⛰️', pista: 'mon-TA-ÑA' },
    { id: 'w26', objetivo: 'naturaleza', texto: 'río', imagen: '🏞️', pista: 'RÍ-O' },
    { id: 'w27', objetivo: 'naturaleza', texto: 'estrella', imagen: '⭐', pista: 'ES-TRE-LA' },
    { id: 'w28', objetivo: 'naturaleza', texto: 'nube', imagen: '☁️', pista: 'NU-BE' },
    { id: 'w29', objetivo: 'medio', texto: 'ambulancia', imagen: '🚑', pista: 'AM-BU-LAN-CIA' },
    { id: 'w30', objetivo: 'medio', texto: 'elefante', imagen: '🐘', pista: 'E-LE-FAN-TE' },
    { id: 'w31', objetivo: 'medio', texto: 'teléfono', imagen: '📱', pista: 'TE-LÉ-FO-NO' },
    { id: 'w32', objetivo: 'medio', texto: 'computadora', imagen: '💻', pista: 'COM-PU-TA-DO-RA' }
  ],

  obtenerEjercicios() { return this.ejercicios; }
};
